DROP INDEX IDX_ITE_03 on items;
GO

CREATE NONCLUSTERED INDEX IDX_ITE_03 on items (userId) include (parentItemName, contextItemName)
GO

DROP INDEX IDX_TAG_NAME_CTX_TYPE ON tags
GO
ALTER TABLE tags
  ALTER COLUMN name NVARCHAR(150) NOT NULL
GO
ALTER TABLE tags
  ALTER COLUMN type NVARCHAR(150) NOT NULL
GO
CREATE UNIQUE NONCLUSTERED INDEX IDX_TAG_NAME_CTX_TYPE
  ON tags (name, contextItemName, type)
GO
