alter table TB_PUBLISHING_JOBS
	add UPDATE_PUBLISH_STATES smallint;

update TB_PUBLISHING_JOBS set UPDATE_PUBLISH_STATES = 0;

alter table TB_WORK_PACKAGES
	add STATUS_CHANGE_DATE timestamp;

REORG table TB_PUBLISHING_JOBS;

REORG table TB_WORK_PACKAGES;
