ALTER TABLE OBJECT_DATA ADD COLUMN objectDataPath VARCHAR(765) DEFAULT NULL;
ALTER TABLE OBJECT_DATA ADD COLUMN versionLabel VARCHAR(255) DEFAULT NULL;
ALTER TABLE OBJECT_DATA ADD COLUMN versionSeriesId VARCHAR(255) DEFAULT NULL;
ALTER TABLE OBJECT_DATA ADD COLUMN isLatestVersion VARCHAR(255) DEFAULT NULL;
ALTER TABLE OBJECT_DATA ADD COLUMN uniquePathCheck VARCHAR(64) UNIQUE;

CREATE INDEX ODILV_IDX ON OBJECT_DATA (isLatestVersion);
CREATE INDEX ODVL_IDX ON OBJECT_DATA (versionLabel);
CREATE INDEX ODVSID_IDX ON OBJECT_DATA (versionSeriesId);
CREATE INDEX ODPATH_IDX ON OBJECT_DATA (objectDataPath(255));

CREATE INDEX FK_PDEF_IDX_OBJ_ID ON PROPERTY_DEFINITION (objectId);
CREATE INDEX FK_RND_IDX_CONTENT_STREAM_ID ON RENDITION (CS_ID);
