ALTER TABLE dbo.OBJECT_TYPE_DEFINITION ALTER COLUMN baseType NVARCHAR(255);
ALTER TABLE dbo.OBJECT_TYPE_DEFINITION ALTER COLUMN contentStreamAllowed NVARCHAR(255);
ALTER TABLE dbo.OBJECT_TYPE_DEFINITION ALTER COLUMN description NVARCHAR(255);
ALTER TABLE dbo.OBJECT_TYPE_DEFINITION ALTER COLUMN displayName NVARCHAR(255);
ALTER TABLE dbo.OBJECT_TYPE_DEFINITION ALTER COLUMN localName NVARCHAR(255);
ALTER TABLE dbo.OBJECT_TYPE_DEFINITION ALTER COLUMN localNamespace NVARCHAR(255);
ALTER TABLE dbo.OBJECT_TYPE_DEFINITION ALTER COLUMN queryName NVARCHAR(255);

ALTER TABLE dbo.PROPERTY_DATA ALTER COLUMN displayName NVARCHAR(255);
ALTER TABLE dbo.PROPERTY_DATA ALTER COLUMN localName NVARCHAR(255);
ALTER TABLE dbo.PROPERTY_DATA ALTER COLUMN queryName NVARCHAR(255);
ALTER TABLE dbo.PROPERTY_DATA ALTER COLUMN value NVARCHAR(765);

ALTER TABLE dbo.PROPERTY_DEFINITION ALTER COLUMN cardinality NVARCHAR(255);
ALTER TABLE dbo.PROPERTY_DEFINITION ALTER COLUMN description NVARCHAR(255);
ALTER TABLE dbo.PROPERTY_DEFINITION ALTER COLUMN displayName NVARCHAR(255);
ALTER TABLE dbo.PROPERTY_DEFINITION ALTER COLUMN localName NVARCHAR(255);
ALTER TABLE dbo.PROPERTY_DEFINITION ALTER COLUMN localNamespace NVARCHAR(255);
ALTER TABLE dbo.PROPERTY_DEFINITION ALTER COLUMN queryName NVARCHAR(255);
ALTER TABLE dbo.PROPERTY_DEFINITION ALTER COLUMN type NVARCHAR(255);
ALTER TABLE dbo.PROPERTY_DEFINITION ALTER COLUMN updatability NVARCHAR(255);

ALTER TABLE dbo.RENDITION ALTER COLUMN filePath NVARCHAR(765);
ALTER TABLE dbo.RENDITION ALTER COLUMN kind NVARCHAR(255);
ALTER TABLE dbo.RENDITION ALTER COLUMN mimeType NVARCHAR(255);
ALTER TABLE dbo.RENDITION ALTER COLUMN renditionDocumentId NVARCHAR(255);
ALTER TABLE dbo.RENDITION ALTER COLUMN title NVARCHAR(255);
ALTER TABLE dbo.RENDITION ALTER COLUMN streamId NVARCHAR(255);