ALTER TABLE OBJECT_DATA ALTER COLUMN path VARCHAR(765);
ALTER TABLE OBJECT_DATA ALTER COLUMN versionLabel VARCHAR(255);
ALTER TABLE OBJECT_DATA ALTER COLUMN versionSeriesId VARCHAR(255);
ALTER TABLE OBJECT_DATA ALTER COLUMN isLatestVersion VARCHAR(255);
ALTER TABLE OBJECT_DATA ALTER COLUMN uniquePathCheck VARCHAR(64);

CREATE INDEX ODILV_IDX ON OBJECT_DATA (isLatestVersion);
CREATE INDEX ODVL_IDX ON OBJECT_DATA (versionLabel);
CREATE INDEX ODVSID_IDX ON OBJECT_DATA (versionSeriesId);
CREATE INDEX ODPATH_IDX ON OBJECT_DATA (path);

CREATE INDEX FK_PDEF_IDX_OBJ_ID ON PROPERTY_DEFINITION (objectId);
CREATE INDEX FK_RND_IDX_CONTENT_STREAM_ID ON RENDITION (CS_ID);

UPDATE OBJECT_DATA SET path = (
  SELECT pd.value FROM PROPERTY_DATA pd
  WHERE pd.objectId = 'cmis:path' AND pd.OBJECT_DATA_ID = OBJECT_DATA.id
);

UPDATE OBJECT_DATA SET versionSeriesId = (
  SELECT pd.value FROM PROPERTY_DATA pd
  WHERE pd.objectId = 'cmis:versionSeriesId' AND pd.OBJECT_DATA_ID = OBJECT_DATA.id
);

UPDATE OBJECT_DATA SET isLatestVersion = (
  SELECT pd.value FROM PROPERTY_DATA pd
  WHERE pd.objectId = 'cmis:isLatestVersion' AND pd.OBJECT_DATA_ID = OBJECT_DATA.id
);

UPDATE OBJECT_DATA SET versionLabel = (
  SELECT pd.value FROM  PROPERTY_DATA pd
  WHERE pd.objectId = 'cmis:versionLabel' AND pd.OBJECT_DATA_ID = OBJECT_DATA.id
);

UPDATE OBJECT_DATA SET isLatestVersion = 'true'
WHERE isLatestVersion IS NULL;

UPDATE OBJECT_DATA SET versionLabel = '1.0'
WHERE versionLabel IS NULL AND versionSeriesId IS NOT NULL;

ALTER TABLE OBJECT_DATA ALTER COLUMN path VARCHAR(765) NOT NULL;
ALTER TABLE OBJECT_DATA ALTER COLUMN uniquePathCheck VARCHAR(64) NOT NULL;
ALTER TABLE OBJECT_DATA ADD CONSTRAINT UQPC UNIQUE(uniquePathCheck);

