ALTER TABLE OBJECT_DATA
    ADD RD_REPOSITORY_ID varchar(36);

UPDATE OBJECT_DATA od SET  od.RD_REPOSITORY_ID = (SELECT rd.REPOSITORY_ID FROM REPOSITORY_DEFINITION rd WHERE  od.RD_ID = rd.id);

ALTER TABLE OBJECT_DATA MODIFY (RD_REPOSITORY_ID VARCHAR(36) NOT NULL) ;

ALTER TABLE OBJECT_DATA DROP CONSTRAINT FK_6gu2if5arkmusbvrssixki55r;

DROP INDEX FK_OD_IDX_OD_RD_REPOID;

CREATE INDEX FK_OD_IDX_OD_RD_REPOID ON OBJECT_DATA (RD_REPOSITORY_ID);

ALTER TABLE OBJECT_DATA
    ADD CONSTRAINT FK_6gu2if5arkmusbvrssixki55r
    FOREIGN KEY (RD_REPOSITORY_ID)
    REFERENCES REPOSITORY_DEFINITION (REPOSITORY_ID);

ALTER TABLE OBJECT_DATA
    DROP COLUMN RD_ID;

ALTER TABLE RELATIONSHIPS ADD sourceObjectId VARCHAR(36);

UPDATE RELATIONSHIPS rel SET rel.sourceObjectId = (SELECT obj.objectId FROM OBJECT_DATA obj WHERE rel.sourceId = obj.id);

ALTER TABLE RELATIONSHIPS MODIFY sourceObjectId VARCHAR(36) NOT NULL;

ALTER TABLE OBJECT_DATA
    ADD objectTypeId varchar(255);

UPDATE OBJECT_DATA od
    SET  od.objectTypeId = (SELECT otd.objectId FROM OBJECT_TYPE_DEFINITION otd WHERE otd.id = od.OBJECT_TYPE_ID);

ALTER TABLE OBJECT_DATA DROP CONSTRAINT FK_354y502ct1ju7tg6v1rlfpwgo;

ALTER TABLE PROPERTY_DEFINITION DROP CONSTRAINT FK_s6scxspskrpjulqsj4u98us2g;

ALTER TABLE PROPERTY_DATA DROP CONSTRAINT FK_c2yshju50dy6nutodteogo28t;

ALTER TABLE OBJECT_DATA
    DROP COLUMN OBJECT_TYPE_ID ;

ALTER TABLE PROPERTY_DATA
    DROP COLUMN PROPERTY_DEFINITION_ID ;

DROP TABLE OBJECT_TYPE_DEFINITION;

DROP TABLE PROPERTY_DEFINITION;

ALTER TABLE OBJECT_DATA MODIFY objectTypeId VARCHAR(255) not null;

CREATE INDEX OD_OBJECID_IDX ON OBJECT_DATA(OBJECTID, RD_REPOSITORY_ID);

CREATE INDEX OD_RS_SOURCEID_IDX ON RELATIONSHIPS(SOURCEID);

CREATE INDEX OD_RS_SOURCEOBJECTID_IDX ON RELATIONSHIPS(SOURCEOBJECTID);


