CREATE TABLE `CONTENT_STREAM` (`id` BIGINT AUTO_INCREMENT NOT NULL,
                               `CONTENT` LONGBLOB NOT NULL,
                               CONSTRAINT `PK_CONTENT_STREAM` PRIMARY KEY (`id`));
ALTER TABLE `OBJECT_DATA` ADD `CS_ID` BIGINT;
ALTER TABLE `RENDITION` ADD `CS_ID` BIGINT UNIQUE;
ALTER TABLE `OBJECT_DATA` DROP COLUMN `STREAMID`;

ALTER TABLE `OBJECT_DATA` ADD CONSTRAINT `OBJECT_DATA_CONTENT_STREAM_FK` FOREIGN KEY (`CS_ID`) REFERENCES `CONTENT_STREAM` (`id`);
ALTER TABLE `RENDITION` ADD CONSTRAINT `RENDITION_CONTENT_STREAM_FK` FOREIGN KEY (`CS_ID`) REFERENCES `CONTENT_STREAM` (`id`);

CREATE INDEX FK_PD_IDX_OBJECTID ON PROPERTY_DATA(OBJECTID);