CREATE INDEX IDX_ACL_ENTRY_SIDACE ON ACL_ENTRY(ID, SID, ACE_ORDER);

CREATE INDEX IDX_ACL_OBJ_ID_SID on ACL_OBJECT_IDENTITY(OWNER_SID);

CREATE INDEX IDX_ACL_OBJID_IDID on ACL_OBJECT_IDENTITY(OBJECT_ID_IDENTITY, OBJECT_ID_CLASS, OWNER_SID);

CREATE INDEX IDX_ACL_ENTRY_SID on ACL_ENTRY(SID);