ALTER TABLE OBJECT_DATA ALTER COLUMN objectDataPath SET NOT NULL;
ALTER TABLE OBJECT_DATA ALTER COLUMN uniquePathCheck SET NOT NULL;

REORG TABLE OBJECT_DATA;

ALTER TABLE OBJECT_DATA ADD CONSTRAINT UQPC UNIQUE(uniquePathCheck);

REORG TABLE OBJECT_DATA;