CREATE TABLE [dbo].[CONTENT_STREAM] ([id] BIGINT IDENTITY NOT NULL, [CONTENT] IMAGE NOT NULL, CONSTRAINT [PK_CONTENT_STREAM] PRIMARY KEY ([id]))
GO
ALTER TABLE [dbo].[OBJECT_DATA] ADD [CS_ID] BIGINT
GO
ALTER TABLE [dbo].[RENDITION] ADD [CS_ID] BIGINT
GO
ALTER TABLE [dbo].[OBJECT_DATA] DROP COLUMN [STREAMID]
GO

ALTER TABLE [dbo].[OBJECT_DATA] ADD CONSTRAINT [OBJECT_DATA_CONTENT_STREAM_FK] FOREIGN KEY ([CS_ID]) REFERENCES [dbo].[CONTENT_STREAM] ([id])
GO
ALTER TABLE [dbo].[RENDITION] ADD CONSTRAINT [RENDITION_CONTENT_STREAM_FK] FOREIGN KEY ([CS_ID]) REFERENCES [dbo].[CONTENT_STREAM] ([id])
GO

CREATE INDEX [FK_OD_IDX_PARENT] ON [dbo].[OBJECT_DATA]([PARENT_ID])
GO
CREATE INDEX [FK_OD_IDX_CS_ID] ON [dbo].[OBJECT_DATA]([CS_ID])
GO
CREATE INDEX [FK_OD_IDX_OBJECT_TYPE_ID] ON [dbo].[OBJECT_DATA]([OBJECT_TYPE_ID])
GO
CREATE INDEX [FK_OTD_IDX_PARENT] ON [dbo].[OBJECT_TYPE_DEFINITION]([PARENT_ID])
GO
CREATE INDEX [FK_PD_IDX_OBJECT_DATA_ID] ON [dbo].[PROPERTY_DATA]([OBJECT_DATA_ID])
GO
CREATE INDEX [FK_PD_IDX_OBJECTID] ON [dbo].[PROPERTY_DATA]([OBJECTID])
GO
CREATE INDEX [FK_PD_IDX_PROP_DEF_ID] ON [dbo].[PROPERTY_DATA]([PROPERTY_DEFINITION_ID])
GO
CREATE INDEX [FK_PDEF_IDX_OBJECT_TYPE_ID] ON [dbo].[PROPERTY_DEFINITION]([OBJECT_TYPE_ID])
GO
CREATE INDEX [FK_RND_IDX_OBJECT_DATA_ID] ON [dbo].[RENDITION]([OBJECT_DATA_ID])
GO