CREATE TABLE CONTENT_STREAM (id NUMBER(19,0) NOT NULL, CONTENT BLOB NOT NULL, CONSTRAINT PK_CONTENT_STREAM PRIMARY KEY (id));
ALTER TABLE OBJECT_DATA ADD CS_ID NUMBER(19,0);
ALTER TABLE RENDITION ADD CS_ID NUMBER(19,0);
ALTER TABLE OBJECT_DATA DROP COLUMN STREAMID;

ALTER TABLE OBJECT_DATA ADD CONSTRAINT OBJECT_DATA_CONTENT_STREAM_FK FOREIGN KEY (CS_ID) REFERENCES CONTENT_STREAM (id);
ALTER TABLE RENDITION ADD CONSTRAINT RENDITION_CONTENT_STREAM_FK FOREIGN KEY (CS_ID) REFERENCES CONTENT_STREAM (id);
CREATE INDEX FK_OD_IDX_PARENT ON OBJECT_DATA(PARENT_ID);
CREATE INDEX FK_OD_IDX_CS_ID ON OBJECT_DATA(CS_ID);
CREATE INDEX FK_OD_IDX_OBJECT_TYPE_ID ON OBJECT_DATA(OBJECT_TYPE_ID);
CREATE INDEX FK_OTD_IDX_PARENT ON OBJECT_TYPE_DEFINITION(PARENT_ID);
CREATE INDEX FK_PD_IDX_OBJECT_DATA_ID ON PROPERTY_DATA(OBJECT_DATA_ID);
CREATE INDEX FK_PD_IDX_OBJECTID ON PROPERTY_DATA(OBJECTID);
CREATE INDEX FK_PD_IDX_PROP_DEF_ID ON PROPERTY_DATA(PROPERTY_DEFINITION_ID);
CREATE INDEX FK_PDEF_IDX_OBJECT_TYPE_ID ON PROPERTY_DEFINITION(OBJECT_TYPE_ID);
CREATE INDEX FK_RND_IDX_OBJECT_DATA_ID ON RENDITION(OBJECT_DATA_ID);