CREATE INDEX OD_OBJECID_IDX ON OBJECT_DATA(OBJECTID, RD_REPOSITORY_ID);

CREATE INDEX OD_RS_SOURCEID_IDX ON RELATIONSHIPS(SOURCEID);

CREATE INDEX OD_RS_SOURCEOBJECTID_IDX ON RELATIONSHIPS(SOURCEOBJECTID);
