ALTER TABLE OBJECT_DATA ADD COLUMN RD_REPOSITORY_ID VARCHAR(36);

CALL SYSPROC.ADMIN_CMD('REORG TABLE OBJECT_DATA');

UPDATE OBJECT_DATA od SET od.RD_REPOSITORY_ID = (
  SELECT rd.REPOSITORY_ID FROM REPOSITORY_DEFINITION rd WHERE rd.id = od.RD_ID
);

ALTER TABLE OBJECT_DATA ALTER COLUMN RD_REPOSITORY_ID SET NOT NULL;

ALTER TABLE OBJECT_DATA DROP FOREIGN KEY FK_6gu2if5arkmusbvrssixki55r;

DROP INDEX FK_OD_IDX_OD_RD_REPOID;

CALL SYSPROC.ADMIN_CMD('REORG TABLE OBJECT_DATA');

CREATE INDEX FK_OD_IDX_OD_RD_REPOID ON OBJECT_DATA (RD_REPOSITORY_ID);

ALTER TABLE OBJECT_DATA
  ADD CONSTRAINT FK_6gu2if5arkmusbvrssixki55r
  FOREIGN KEY (RD_REPOSITORY_ID)
  REFERENCES REPOSITORY_DEFINITION (REPOSITORY_ID);

ALTER TABLE OBJECT_DATA DROP COLUMN RD_ID;

CALL SYSPROC.ADMIN_CMD('REORG TABLE OBJECT_DATA');

ALTER TABLE RELATIONSHIPS ADD COLUMN sourceObjectId VARCHAR(36);
REORG INDEXES ALL FOR TABLE RELATIONSHIPS;

UPDATE RELATIONSHIPS rel SET rel.sourceObjectId = (
  SELECT obj.objectId FROM OBJECT_DATA obj WHERE obj.id = rel.sourceId
);

ALTER TABLE RELATIONSHIPS ALTER COLUMN sourceObjectId SET NOT NULL;

CALL SYSPROC.ADMIN_CMD('REORG TABLE RELATIONSHIPS');

ALTER TABLE OBJECT_DATA ADD COLUMN objectTypeId VARCHAR(255);

UPDATE OBJECT_DATA od SET od.objectTypeId = (
  select objectId from OBJECT_TYPE_DEFINITION otd where od.OBJECT_TYPE_ID = otd.id
);

ALTER TABLE OBJECT_DATA DROP FOREIGN KEY FK_354y502ct1ju7tg6v1rlfpwgo;

ALTER TABLE PROPERTY_DEFINITION DROP FOREIGN KEY  FK_s6scxspskrpjulqsj4u98us2g;

ALTER TABLE PROPERTY_DATA DROP FOREIGN KEY  FK_c2yshju50dy6nutodteogo28t;

ALTER TABLE OBJECT_DATA DROP COLUMN OBJECT_TYPE_ID;

ALTER TABLE PROPERTY_DATA DROP COLUMN PROPERTY_DEFINITION_ID;

CALL SYSPROC.ADMIN_CMD('REORG TABLE PROPERTY_DATA');

DROP TABLE OBJECT_TYPE_DEFINITION;

DROP TABLE PROPERTY_DEFINITION;

ALTER TABLE OBJECT_DATA ALTER COLUMN  objectTypeId SET NOT NULL;

CALL SYSPROC.ADMIN_CMD('REORG TABLE OBJECT_DATA');
