ALTER TABLE OBJECT_DATA ALTER COLUMN objectDataPath NVARCHAR(765) NOT NULL;
CREATE INDEX ODPATH_IDX ON OBJECT_DATA (objectDataPath);
ALTER TABLE OBJECT_DATA ALTER COLUMN uniquePathCheck NVARCHAR(64) NOT NULL;
ALTER TABLE OBJECT_DATA ADD CONSTRAINT UQPC UNIQUE(uniquePathCheck);

