ALTER TABLE OBJECT_TYPE_DEFINITION ALTER COLUMN baseType NVARCHAR(255);
ALTER TABLE OBJECT_TYPE_DEFINITION ALTER COLUMN contentStreamAllowed NVARCHAR(255);
ALTER TABLE OBJECT_TYPE_DEFINITION ALTER COLUMN description NVARCHAR(255);
ALTER TABLE OBJECT_TYPE_DEFINITION ALTER COLUMN displayName NVARCHAR(255);
ALTER TABLE OBJECT_TYPE_DEFINITION ALTER COLUMN localName NVARCHAR(255);
ALTER TABLE OBJECT_TYPE_DEFINITION ALTER COLUMN localNamespace NVARCHAR(255);
ALTER TABLE OBJECT_TYPE_DEFINITION ALTER COLUMN queryName NVARCHAR(255);

ALTER TABLE PROPERTY_DATA ALTER COLUMN displayName NVARCHAR(255);
ALTER TABLE PROPERTY_DATA ALTER COLUMN localName NVARCHAR(255);
ALTER TABLE PROPERTY_DATA ALTER COLUMN queryName NVARCHAR(255);
ALTER TABLE PROPERTY_DATA ALTER COLUMN value NVARCHAR(765);

ALTER TABLE PROPERTY_DEFINITION ALTER COLUMN cardinality NVARCHAR(255);
ALTER TABLE PROPERTY_DEFINITION ALTER COLUMN description NVARCHAR(255);
ALTER TABLE PROPERTY_DEFINITION ALTER COLUMN displayName NVARCHAR(255);
ALTER TABLE PROPERTY_DEFINITION ALTER COLUMN localName NVARCHAR(255);
ALTER TABLE PROPERTY_DEFINITION ALTER COLUMN localNamespace NVARCHAR(255);
ALTER TABLE PROPERTY_DEFINITION ALTER COLUMN queryName NVARCHAR(255);
ALTER TABLE PROPERTY_DEFINITION ALTER COLUMN type NVARCHAR(255);
ALTER TABLE PROPERTY_DEFINITION ALTER COLUMN updatability NVARCHAR(255);

ALTER TABLE RENDITION ALTER COLUMN filePath NVARCHAR(765);
ALTER TABLE RENDITION ALTER COLUMN kind NVARCHAR(255);
ALTER TABLE RENDITION ALTER COLUMN mimeType NVARCHAR(255);
ALTER TABLE RENDITION ALTER COLUMN renditionDocumentId NVARCHAR(255);
ALTER TABLE RENDITION ALTER COLUMN title NVARCHAR(255);
ALTER TABLE RENDITION ALTER COLUMN streamId NVARCHAR(255);

ALTER TABLE OBJECT_DATA ADD objectDataPath NVARCHAR(765);
ALTER TABLE OBJECT_DATA ADD versionLabel NVARCHAR(255);
ALTER TABLE OBJECT_DATA ADD versionSeriesId NVARCHAR(255);
ALTER TABLE OBJECT_DATA ADD isLatestVersion NVARCHAR(255);
ALTER TABLE OBJECT_DATA ADD uniquePathCheck NVARCHAR(64);

CREATE INDEX ODILV_IDX ON OBJECT_DATA (isLatestVersion);
CREATE INDEX ODVL_IDX ON OBJECT_DATA (versionLabel);
CREATE INDEX ODVSID_IDX ON OBJECT_DATA (versionSeriesId);

CREATE INDEX FK_PDEF_IDX_OBJ_ID ON PROPERTY_DEFINITION (objectId);
CREATE INDEX FK_RND_IDX_CONTENT_STREAM_ID ON RENDITION (CS_ID);
