ALTER TABLE OBJECT_DATA ADD objectDataPath VARCHAR2(765 char) NULL;
ALTER TABLE OBJECT_DATA ADD versionLabel VARCHAR2(255 char) NULL;
ALTER TABLE OBJECT_DATA ADD versionSeriesId VARCHAR2(255 char) NULL;
ALTER TABLE OBJECT_DATA ADD isLatestVersion VARCHAR2(255 char) NULL;
ALTER TABLE OBJECT_DATA ADD uniquePathCheck VARCHAR2(64 char) NULL;

CREATE INDEX ODILV_IDX ON OBJECT_DATA (isLatestVersion);
CREATE INDEX ODVL_IDX ON OBJECT_DATA (versionLabel);
CREATE INDEX ODVSID_IDX ON OBJECT_DATA (versionSeriesId);
CREATE INDEX ODPATH_IDX ON OBJECT_DATA (objectDataPath);

CREATE INDEX FK_PDEF_IDX_OBJ_ID ON PROPERTY_DEFINITION (objectId);
CREATE INDEX FK_RND_IDX_CONTENT_STREAM_ID ON RENDITION (CS_ID);
